apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-axw5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0048-tenant/ci1t-43256-0048-app/devfile-sample-axw5@sha256:dde70be0cca918048d008e063eabaaa20074a40a01b71fcd458d914a8bda55d6
        name: my-nodejs
        resources: {}
status: {}
